
(DECLARE (SPECIAL %VTYL)) 

(PUTPROP (QUOTE FUN%8734%107905) (QUOTE NIL) (QUOTE CURRYBIND)) 

(DEFUN FUN%8734%107905 (%E) (CAR %E)) 

(EXECUTE (QUOTE (MK-FUNTYP * *)) (QUOTE (LET (|id| MK-FUNTYP * *))) (QUOTE NIL) (QUOTE MK-LET) (QUOTE |MK-LET%id%107904|) (QUOTE (CONS (QUOTE |id|) (CAR (CONS (CONS (QUOTE FUN%8734%107905) %E) NIL))))) 

(PUTPROP (QUOTE FUN%8734%107907) (QUOTE NIL) (QUOTE CURRYBIND)) 

(PUTPROP (QUOTE FUN%8734%107908) (QUOTE NIL) (QUOTE CURRYBIND)) 

(PUTPROP (QUOTE FUN%8734%107909) (QUOTE FUN%8734%107908) (QUOTE CURRYBIND)) 

(DEFUN FUN%8734%107907 (%E) (COND ((AP |MK-LET%is_var_term%72360| (CAR %E)) (ML-EQUAL (ML-DESTRUCT-VAR (CAR %E)) (CADDDR %E))) (((LAMBDA (%E) (COND ((ML-EQUAL (CAR %E) 0) NIL) ((ML-EQUAL (CAR %E) 1) T) ((*THROW (QUOTE EVALUATION) (QUOTE FAIL))))) (CONS (LENGTH (AP (AP |MK-LET%filter%71960| |MK-LET%id%107904|) (AP (AP |MK-LET%map%71945| (CADR %E)) (ML-SUBTERMS (CAR %E))))) %E))))) 

(DEFUN FUN%8734%107908 (%E) ((LAMBDA (%E) ((LAMBDA (B) (COND ((NOT (ATOM B)) (CAR B)) ((*THROW (QUOTE EVALUATION) (QUOTE |more than 1 occurrence|))))) (*CATCH (QUOTE EVALUATION) (LIST (AP (CAR %E) (CADR %E)))))) ((LAMBDA (%E) (RPLACA %E (CONS (QUOTE FUN%8734%107907) %E))) (CONS NIL %E)))) 

(DEFUN FUN%8734%107909 (%E) (CONS (QUOTE FUN%8734%107908) %E)) 

(EXECUTE (QUOTE (MK-FUNTYP (MK-TOKTYP) (MK-FUNTYP (MK-TERMTYP) (MK-BOOLTYP)))) (QUOTE (LET (|occurs_once| MK-FUNTYP (MK-TOKTYP) (MK-FUNTYP (MK-TERMTYP) (MK-BOOLTYP))))) (QUOTE NIL) (QUOTE MK-LET) (QUOTE |MK-LET%occurs_once%107906|) (QUOTE (CONS (QUOTE |occurs_once|) (CAR (CONS (CONS (QUOTE FUN%8734%107909) %E) NIL))))) 

(PUTPROP (QUOTE FUN%8734%107911) (QUOTE NIL) (QUOTE CURRYBIND)) 

(DEFUN FUN%8734%107911 (%E) ((LAMBDA (B) (COND ((NOT (ATOM B)) (CAR B)) ((AP (AP |MK-LET%map_on_subterms%72089| (CADR %E)) (CAR %E))))) (*CATCH (QUOTE EVALUATION) (LIST ((LAMBDA (%E) ((LAMBDA (%E) (COND ((AP (AP |MK-LET%occurs_once%107906| (CAAR %E)) (CDAR %E)) (AP (CADDDR %E) (AP (AP |MK-LET%substitute%72086| (CDAR %E)) (LIST (CONS (AP |MK-LET%mvt%40911| (CAAR %E)) (CDADR %E)))))) ((AP (CADDDR %E) (CDAR %E))))) (CONS (ML-DESTRUCT-LAMBDA (CAAR %E)) %E))) (CONS (ML-DESTRUCT-APPLY (CAR %E)) %E)))))) 

(EXECUTE (QUOTE (MK-FUNTYP (MK-TERMTYP) (MK-TERMTYP))) (QUOTE (LET (|optimize| MK-FUNTYP (MK-TERMTYP) (MK-TERMTYP)))) (QUOTE NIL) (QUOTE MK-LETREC) (QUOTE |MK-LETREC%optimize%107910|) (QUOTE (CONS (QUOTE |optimize|) (CAR ((LAMBDA (%E) (RPLACA %E (CONS (QUOTE FUN%8734%107911) %E))) (CONS NIL NIL)))))) 

(PUTPROP (QUOTE FUN%8734%107913) (QUOTE NIL) (QUOTE CURRYBIND)) 

(DEFUN FUN%8734%107913 (%E) (COND ((AP |MK-LET%is_function_term%72338| (CAR %E)) (ML-MAKE-TOKEN-TERM (QUOTE |<type>|))) ((AP |MK-LET%is_term_of_theorem_term%72368| (CAR %E)) (AP (CADR %E) (ML-EXTRACTED-TERM-OF-THEOREM (ML-DESTRUCT-TERM-OF-THEOREM (CAR %E))))) ((AP (AP |MK-LET%map_on_subterms%72089| (CADR %E)) (CAR %E))))) 

(EXECUTE (QUOTE (MK-FUNTYP (MK-TERMTYP) (MK-TERMTYP))) (QUOTE (LET (|expand_term| MK-FUNTYP (MK-TERMTYP) (MK-TERMTYP)))) (QUOTE NIL) (QUOTE MK-LETREC) (QUOTE |MK-LETREC%expand_term%107912|) (QUOTE (CONS (QUOTE |expand_term|) (CAR ((LAMBDA (%E) (RPLACA %E (CONS (QUOTE FUN%8734%107913) %E))) (CONS NIL NIL)))))) 

(PUTPROP (QUOTE FUN%8734%107915) (QUOTE NIL) (QUOTE CURRYBIND)) 

(PUTPROP (QUOTE FUN%8734%107916) (QUOTE FUN%8734%107915) (QUOTE CURRYBIND)) 

(PUTPROP (QUOTE FUN%8734%107917) (QUOTE NIL) (QUOTE CURRYBIND)) 

(DEFUN FUN%8734%107915 (%E) (PLUS (CADR %E) (CAR %E))) 

(DEFUN FUN%8734%107916 (%E) (CONS (QUOTE FUN%8734%107915) %E)) 

(DEFUN FUN%8734%107917 (%E) (PLUS 1 (AP (AP (AP |MK-LET%accumulate%41871| (CONS (QUOTE FUN%8734%107916) %E)) 0) (AP (AP |MK-LET%map%71945| (CADR %E)) (ML-SUBTERMS (CAR %E)))))) 

(EXECUTE (QUOTE (MK-FUNTYP (MK-TERMTYP) (MK-INTTYP))) (QUOTE (LET (|number_of_subterms| MK-FUNTYP (MK-TERMTYP) (MK-INTTYP)))) (QUOTE NIL) (QUOTE MK-LETREC) (QUOTE |MK-LETREC%number_of_subterms%107914|) (QUOTE (CONS (QUOTE |number_of_subterms|) (CAR ((LAMBDA (%E) (RPLACA %E (CONS (QUOTE FUN%8734%107917) %E))) (CONS NIL NIL)))))) 
